 <!-- Including Jquery -->
 <script src="{{ asset('frontend/assets/js/vendor/jquery-3.3.1.min.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/jquery.cookie.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/modernizr-3.6.0.min.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/vendor/wow.min.js') }}"></script>
 <!-- Including Javascript -->
 <script src="{{ asset('frontend/assets/js/bootstrap.min.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/plugins.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/popper.min.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/lazysizes.js') }}"></script>
 <script src="{{ asset('frontend/assets/js/main.js') }}"></script>
